// dart format width=80
// ignore_for_file: unused_local_variable, unused_import
import 'package:drift/drift.dart';
import 'package:drift_dev/api/migrations_native.dart';
import 'package:denge/data/db/app_database.dart';
import 'package:flutter_test/flutter_test.dart';
import 'generated/schema.dart';

import 'generated/schema_v1.dart' as v1;
import 'generated/schema_v2.dart' as v2;

/// Migration tests generated by `dart run drift_dev make-migrations`
/// (CLAUDE.md §8). Regenerate the `generated/` folder after every schema
/// change and add a data-integrity test for the new step.
void main() {
  driftRuntimeOptions.dontWarnAboutMultipleDatabases = true;
  late SchemaVerifier verifier;

  setUpAll(() {
    verifier = SchemaVerifier(GeneratedHelper());
  });

  group('simple database migrations', () {
    // Every older schema must migrate to every newer one and end up exactly
    // like a freshly created database.
    const versions = GeneratedHelper.versions;
    for (final (i, fromVersion) in versions.indexed) {
      group('from $fromVersion', () {
        for (final toVersion in versions.skip(i + 1)) {
          test('to $toVersion', () async {
            final schema = await verifier.schemaAt(fromVersion);
            final db = AppDatabase.forTesting(schema.newConnection());
            await verifier.migrateAndValidate(db, toVersion);
            await db.close();
          });
        }
      });
    }
  });

  test('migration from v1 to v2 keeps every row and leaves them unsynced',
      () async {
    await verifier.testWithDataIntegrity(
      oldVersion: 1,
      newVersion: 2,
      createOld: v1.DatabaseAtV1.new,
      createNew: v2.DatabaseAtV2.new,
      openTestedDatabase: AppDatabase.forTesting,
      createItems: (batch, oldDb) {
        batch.insertAll(oldDb.foodLogEntries, [
          const v1.FoodLogEntriesData(
            id: 'f1',
            createdAt: 1,
            updatedAt: 2,
            deletedAt: 3,
            date: '2026-10-07',
            meal: 'lunch',
            foodName: 'Menemen',
            brand: 'Ev yapımı',
            servingLabel: '1 porsiyon',
            amount: 1.5,
            kcal: 180,
            proteinG: 9.75,
            carbsG: 8.25,
            fatG: 12.3,
            source: 'barcode',
            sourceRef: '869',
            loggedAt: 2,
          ),
        ]);
        batch.insertAll(oldDb.waterLogs, [
          const v1.WaterLogsData(
              id: 'w1', createdAt: 1, updatedAt: 2, date: '2026-10-07',
              glasses: 4),
        ]);
        batch.insertAll(oldDb.weightEntries, [
          const v1.WeightEntriesData(
              id: 'k1', createdAt: 1, updatedAt: 2, date: '2026-10-07',
              kg: 70.4, measuredAt: 2),
        ]);
        batch.insertAll(oldDb.customFoods, [
          const v1.CustomFoodsData(
              id: 'c1', createdAt: 1, updatedAt: 2, name: 'Börek', brand: '',
              servingLabel: '1 dilim', kcalPerServing: 310, proteinG: 9,
              carbsG: 30, fatG: 17, category: 'hamurIsi', barcode: '869'),
        ]);
      },
      validateItems: (newDb) async {
        expect(await newDb.select(newDb.foodLogEntries).get(), [
          const v2.FoodLogEntriesData(
            id: 'f1',
            createdAt: 1,
            updatedAt: 2,
            deletedAt: 3,
            date: '2026-10-07',
            meal: 'lunch',
            foodName: 'Menemen',
            brand: 'Ev yapımı',
            servingLabel: '1 porsiyon',
            amount: 1.5,
            kcal: 180,
            proteinG: 9.75,
            carbsG: 8.25,
            fatG: 12.3,
            source: 'barcode',
            sourceRef: '869',
            loggedAt: 2,
          ),
        ]);
        expect(await newDb.select(newDb.waterLogs).get(), [
          const v2.WaterLogsData(
              id: 'w1', createdAt: 1, updatedAt: 2, date: '2026-10-07',
              glasses: 4),
        ]);
        expect(await newDb.select(newDb.weightEntries).get(), [
          const v2.WeightEntriesData(
              id: 'k1', createdAt: 1, updatedAt: 2, date: '2026-10-07',
              kg: 70.4, measuredAt: 2),
        ]);
        expect(await newDb.select(newDb.customFoods).get(), [
          const v2.CustomFoodsData(
              id: 'c1', createdAt: 1, updatedAt: 2, name: 'Börek', brand: '',
              servingLabel: '1 dilim', kcalPerServing: 310, proteinG: 9,
              carbsG: 30, fatG: 17, category: 'hamurIsi', barcode: '869'),
        ]);
        // Nothing has been pulled yet.
        expect(await newDb.select(newDb.syncState).get(), isEmpty);
      },
    );
  });
}
