// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    foodLogEntries,
    waterLogs,
    weightEntries,
    customFoods,
    syncState,
    foodLogDateMeal,
    foodLogDate,
  ];
  late final Shape0 foodLogEntries = Shape0(
    source: i0.VersionedTable(
      entityName: 'food_log_entries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 waterLogs = Shape1(
    source: i0.VersionedTable(
      entityName: 'water_logs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_19,
        _column_20,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 weightEntries = Shape2(
    source: i0.VersionedTable(
      entityName: 'weight_entries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_21,
        _column_22,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 customFoods = Shape3(
    source: i0.VersionedTable(
      entityName: 'custom_foods',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_23,
        _column_9,
        _column_10,
        _column_24,
        _column_13,
        _column_14,
        _column_15,
        _column_25,
        _column_26,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 syncState = Shape4(
    source: i0.VersionedTable(
      entityName: 'sync_state',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(entity)'],
      columns: [_column_27, _column_28],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index foodLogDateMeal = i1.Index(
    'food_log_date_meal',
    'CREATE INDEX food_log_date_meal ON food_log_entries (date, meal)',
  );
  final i1.Index foodLogDate = i1.Index(
    'food_log_date',
    'CREATE INDEX food_log_date ON food_log_entries (date)',
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get deletedAt =>
      columnsByName['deleted_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get syncedAt =>
      columnsByName['synced_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get serverUpdatedAt =>
      columnsByName['server_updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get date =>
      columnsByName['date']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get meal =>
      columnsByName['meal']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get foodName =>
      columnsByName['food_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get brand =>
      columnsByName['brand']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get servingLabel =>
      columnsByName['serving_label']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get amount =>
      columnsByName['amount']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get kcal =>
      columnsByName['kcal']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get proteinG =>
      columnsByName['protein_g']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get carbsG =>
      columnsByName['carbs_g']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get fatG =>
      columnsByName['fat_g']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get source =>
      columnsByName['source']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sourceRef =>
      columnsByName['source_ref']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get loggedAt =>
      columnsByName['logged_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_0(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_1(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'created_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_2(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'updated_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_3(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'deleted_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_4(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'synced_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_5(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'server_updated_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_6(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'date',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_7(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'meal',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_8(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'food_name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_9(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'brand',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'\'',
      defaultValue: const i1.CustomExpression('\'\''),
    );
i1.GeneratedColumn<String> _column_10(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'serving_label',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_11(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'amount',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_12(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'kcal',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_13(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'protein_g',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_14(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'carbs_g',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_15(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'fat_g',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_16(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'source',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_17(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'source_ref',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_18(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'logged_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get deletedAt =>
      columnsByName['deleted_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get syncedAt =>
      columnsByName['synced_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get serverUpdatedAt =>
      columnsByName['server_updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get date =>
      columnsByName['date']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get glasses =>
      columnsByName['glasses']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_19(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'date',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL UNIQUE',
    );
i1.GeneratedColumn<int> _column_20(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'glasses',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get deletedAt =>
      columnsByName['deleted_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get syncedAt =>
      columnsByName['synced_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get serverUpdatedAt =>
      columnsByName['server_updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get date =>
      columnsByName['date']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get kg =>
      columnsByName['kg']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get measuredAt =>
      columnsByName['measured_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<double> _column_21(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'kg',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_22(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'measured_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get deletedAt =>
      columnsByName['deleted_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get syncedAt =>
      columnsByName['synced_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get serverUpdatedAt =>
      columnsByName['server_updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get brand =>
      columnsByName['brand']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get servingLabel =>
      columnsByName['serving_label']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get kcalPerServing =>
      columnsByName['kcal_per_serving']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get proteinG =>
      columnsByName['protein_g']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get carbsG =>
      columnsByName['carbs_g']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get fatG =>
      columnsByName['fat_g']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get category =>
      columnsByName['category']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get barcode =>
      columnsByName['barcode']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_23(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_24(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'kcal_per_serving',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_25(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'category',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_26(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'barcode',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get entity =>
      columnsByName['entity']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get pulledUntil =>
      columnsByName['pulled_until']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_27(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'entity',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_28(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'pulled_until',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(from1To2: from1To2),
);
